# Welcome to Numpy Learning by Implemantation

In [1]:
import numpy as np

In [2]:
myarr = np.array([12,24,42,19],np.int8)

In [3]:
myarr

array([12, 24, 42, 19], dtype=int8)

In [4]:
myarr[2]

42

In [6]:
myarr2 = np.array([[12,24,42,19],[14,28,44,76]],np.int8)

In [9]:
myarr2[0][2]

42

In [10]:
myarr2.shape

(2, 4)

In [11]:
myarr2.dtype

dtype('int8')

In [15]:
myarr2[1,3]

76

In [16]:
myarr2[1,3]=82

In [17]:
myarr2[1,3]

82

In [18]:
rang = np.arange(20)

In [19]:
rang

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
lspace = np.linspace(1,10,4)

In [21]:
lspace

array([ 1.,  4.,  7., 10.])

In [23]:
zero = np.zeros((2,5))

In [24]:
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
emp = np.empty((3,4))

In [26]:
emp

array([[8.47591718e-312, 3.16202013e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.01855798e-312, 4.27805397e-037, 4.47118494e-033,
        7.56532595e-067],
       [1.43602097e-051, 1.08589902e-042, 1.38272285e-047,
        1.65747387e-076]])

In [27]:
emp.size

12

In [29]:
emp.shape

(3, 4)

In [30]:
ide = np.identity(10)

In [31]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [32]:
ide.shape

(10, 10)

# *** 2 D Array ***

In [39]:
my_arr = [[13,12,1991,42],[4,12,1989,65],[16,8,2006,78],[6,11,2007,89]]

In [40]:
arr = np.array(my_arr)

In [41]:
arr

array([[  13,   12, 1991,   42],
       [   4,   12, 1989,   65],
       [  16,    8, 2006,   78],
       [   6,   11, 2007,   89]])

In [42]:
arr.sum(axis=1)

array([2058, 2070, 2108, 2113])

In [43]:
arr.sum(axis=0)

array([  39,   43, 7993,  274])

In [45]:
for x in arr.flat:
    print(x)

13
12
1991
42
4
12
1989
65
16
8
2006
78
6
11
2007
89


In [46]:
arr.nbytes

64

In [47]:
arr.ndim

2

** One Dimension Array ** 

In [48]:
my_one = np.array([12,23,1,89,42,19,45])

In [49]:
my_one

array([12, 23,  1, 89, 42, 19, 45])

In [51]:
my_one.argmax()

3

In [52]:
my_one.argmin()

2

In [53]:
my_one.argsort()

array([2, 0, 5, 1, 4, 6, 3], dtype=int64)